all:
  children:
    cluster_nodes:
      hosts:
        node01: { ansible_host: 10.0.0.11 }
        node02: { ansible_host: 10.0.0.12 }
        node03: { ansible_host: 10.0.0.13 }
        node04: { ansible_host: 10.0.0.14 }
        node05: { ansible_host: 10.0.0.15 }
        node06: { ansible_host: 10.0.0.16 }
        node07: { ansible_host: 10.0.0.17 }
        node08: { ansible_host: 10.0.0.18 }
        node09: { ansible_host: 10.0.0.19 }
        node10: { ansible_host: 10.0.0.20 }
        node11: { ansible_host: 10.0.0.21 }
        node12: { ansible_host: 10.0.0.22 }
        node13: { ansible_host: 10.0.0.23 }
        node14: { ansible_host: 10.0.0.24 }
        node15: { ansible_host: 10.0.0.25 }
        node16: { ansible_host: 10.0.0.26 }
        node17: { ansible_host: 10.0.0.27 }
        node18: { ansible_host: 10.0.0.28 }
        node19: { ansible_host: 10.0.0.29 }
        node20: { ansible_host: 10.0.0.30 }
