services:
  dtwarehouse-postgres:
    image: postgres:15
    container_name: dtwarehouse-postgres
    hostname: dtwarehouse-postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hivepassword
    ports:
      - "5433:5432" # PostgreSQL (host:container)
    volumes:
      - ../volumes/dtwarehouse-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - hadoop_network


  dtwarehouse-hive:
    build:
      context: ./hive
    image: data-warehouse-hive:4.1.0
    container_name: dtwarehouse-hive
    hostname: dtwarehouse-hive
    environment:
      - SERVICE_NAME=hiveserver2
    depends_on:
      dtwarehouse-postgres:
        condition: service_healthy
    ports:
      - "10000:10000" # HiveServer2
      - "10002:10002" # Web UI
      - "9083:9083" # Metastore thrift
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'bash -lc "timeout 2 bash -lc ''</dev/tcp/127.0.0.1/9083'' && timeout 2 bash -lc ''</dev/tcp/127.0.0.1/10000''"',
        ]
      interval: 15s
      timeout: 5s
      retries: 12
      start_period: 60s
    volumes:
      - ../volumes/hive/warehouse:/warehouse
    networks:
      - hadoop_network

  # dtwarehouse-hbase:
  #   build:
  #     context: ./hbase
  #   image: data-warehouse-hbase:2.4.17
  #   container_name: dtwarehouse-hbase
  #   hostname: dtwarehouse-hbase
  #   depends_on:
  #     dtwarehouse-zookeeper:
  #       condition: service_healthy
  #   ports:
  #     - "16010:16010" # HBase Master UI
  #     - "16000:16000" # HBase Master RPC
  #   volumes:
  #     - ../volumes/hbase:/opt/hbase-data
  #   networks:
  #     - hadoop_network
  # dtwarehouse-zookeeper:
  #   image: zookeeper:3.8
  #   container_name: dtwarehouse-zookeeper
  #   hostname: dtwarehouse-zookeeper
  #   ports:
  #     - "2181:2181" # ZooKeeper client
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         'bash -lc "timeout 2 bash -lc ''</dev/tcp/127.0.0.1/2181''"',
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 20s
  #   networks:
  #     - hadoop_network


networks:
  hadoop_network:
    external: true
